-- ============================================================
-- PROYECTO 01 - TI6900 Inteligencia de Negocios
-- Grupo 02 - Tema 2: Plataforma de comercio electrónico
-- Persona 2 - Implementación del modelo dimensional
-- Motor: PostgreSQL
--
-- IMPORTANTE:
-- 1) Ejecutar este script dentro de la misma base de datos que contiene
--    la fuente transaccional de Persona 1 en el esquema public.
-- 2) Este script CREA la estructura del Data Warehouse en el esquema dw.
-- 3) No carga los datos de negocio desde public hacia dw; esa carga
--    corresponde al proceso ETL de Persona 3.
-- ============================================================


-- ============================================================
-- 1. CREACIÓN DEL ESQUEMA DEL DATA WAREHOUSE
-- ============================================================

CREATE SCHEMA IF NOT EXISTS dw;

COMMENT ON SCHEMA dw IS
'Esquema dimensional del Data Warehouse para la plataforma de comercio electrónico del Grupo 02.';


-- ============================================================
-- 2. DIMENSIONES
-- ============================================================

-- ------------------------------------------------------------
-- 2.1 DimTiempo
-- ------------------------------------------------------------
CREATE TABLE dw.dim_tiempo (
    sk_tiempo      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha           DATE UNIQUE,
    dia             INTEGER,
    nombre_dia      VARCHAR(20),
    semana          INTEGER,
    mes             INTEGER,
    nombre_mes      VARCHAR(20),
    trimestre       INTEGER,
    anio            INTEGER
);

COMMENT ON TABLE dw.dim_tiempo IS
'Dimensión de tiempo conformada. Se reutiliza con distintos roles: fecha de pedido, fecha prevista, fecha de entrega real y fecha de evento.';

COMMENT ON COLUMN dw.dim_tiempo.sk_tiempo IS 'Llave subrogada de la dimensión de tiempo.';
COMMENT ON COLUMN dw.dim_tiempo.fecha IS 'Fecha calendario representada por la fila.';
COMMENT ON COLUMN dw.dim_tiempo.dia IS 'Número de día del mes.';
COMMENT ON COLUMN dw.dim_tiempo.nombre_dia IS 'Nombre del día de la semana.';
COMMENT ON COLUMN dw.dim_tiempo.semana IS 'Número de semana del año.';
COMMENT ON COLUMN dw.dim_tiempo.mes IS 'Número de mes.';
COMMENT ON COLUMN dw.dim_tiempo.nombre_mes IS 'Nombre del mes.';
COMMENT ON COLUMN dw.dim_tiempo.trimestre IS 'Trimestre calendario, de 1 a 4.';
COMMENT ON COLUMN dw.dim_tiempo.anio IS 'Año calendario.';


-- ------------------------------------------------------------
-- 2.2 DimCliente
-- ------------------------------------------------------------
CREATE TABLE dw.dim_cliente (
    sk_cliente          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente_origen   INTEGER UNIQUE,
    nombre_cliente      VARCHAR(100) NOT NULL,
    tipo_cliente        VARCHAR(20),
    fecha_registro      DATE
);

COMMENT ON TABLE dw.dim_cliente IS
'Dimensión de clientes construida a partir de public.cliente.';

COMMENT ON COLUMN dw.dim_cliente.sk_cliente IS 'Llave subrogada de la dimensión.';
COMMENT ON COLUMN dw.dim_cliente.id_cliente_origen IS 'Identificador del cliente en la fuente transaccional.';
COMMENT ON COLUMN dw.dim_cliente.nombre_cliente IS 'Nombre del cliente.';
COMMENT ON COLUMN dw.dim_cliente.tipo_cliente IS 'Segmento del cliente: Nuevo, Recurrente o VIP, según la fuente.';
COMMENT ON COLUMN dw.dim_cliente.fecha_registro IS 'Fecha de registro del cliente en la plataforma.';


-- ------------------------------------------------------------
-- 2.3 DimProducto
-- ------------------------------------------------------------
CREATE TABLE dw.dim_producto (
    sk_producto          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto_origen   INTEGER UNIQUE,
    nombre_producto      VARCHAR(150) NOT NULL,
    nombre_categoria     VARCHAR(50) NOT NULL,
    nombre_marca         VARCHAR(50) NOT NULL
);

COMMENT ON TABLE dw.dim_producto IS
'Dimensión desnormalizada de producto. Integra información de public.producto, public.categoria y public.marca.';

COMMENT ON COLUMN dw.dim_producto.sk_producto IS 'Llave subrogada de la dimensión.';
COMMENT ON COLUMN dw.dim_producto.id_producto_origen IS 'Identificador del producto en la fuente transaccional.';
COMMENT ON COLUMN dw.dim_producto.nombre_producto IS 'Nombre del producto.';
COMMENT ON COLUMN dw.dim_producto.nombre_categoria IS 'Nombre de la categoría del producto.';
COMMENT ON COLUMN dw.dim_producto.nombre_marca IS 'Nombre de la marca del producto.';


-- ------------------------------------------------------------
-- 2.4 DimCampania
-- ------------------------------------------------------------
CREATE TABLE dw.dim_campania (
    sk_campania          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_campania_origen   INTEGER UNIQUE,
    nombre_campania      VARCHAR(100) NOT NULL,
    tipo_descuento       VARCHAR(20),
    valor_descuento      NUMERIC(10,2),
    fecha_inicio         DATE,
    fecha_fin            DATE
);

COMMENT ON TABLE dw.dim_campania IS
'Dimensión de campañas construida a partir de public.campania. Incluye un miembro técnico para pedidos sin campaña.';

COMMENT ON COLUMN dw.dim_campania.sk_campania IS 'Llave subrogada de la dimensión.';
COMMENT ON COLUMN dw.dim_campania.id_campania_origen IS 'Identificador de la campaña en la fuente transaccional.';
COMMENT ON COLUMN dw.dim_campania.nombre_campania IS 'Nombre de la campaña.';
COMMENT ON COLUMN dw.dim_campania.tipo_descuento IS 'Tipo de descuento de la campaña.';
COMMENT ON COLUMN dw.dim_campania.valor_descuento IS 'Valor del descuento definido para la campaña.';
COMMENT ON COLUMN dw.dim_campania.fecha_inicio IS 'Fecha de inicio de la campaña.';
COMMENT ON COLUMN dw.dim_campania.fecha_fin IS 'Fecha de finalización de la campaña.';


-- ------------------------------------------------------------
-- 2.5 DimContextoPedido
-- ------------------------------------------------------------
CREATE TABLE dw.dim_contexto_pedido (
    sk_contexto_pedido   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canal_dispositivo    VARCHAR(30),
    metodo_pago          VARCHAR(30),
    estado_pedido        VARCHAR(20),

    CONSTRAINT uq_dim_contexto_pedido
        UNIQUE (canal_dispositivo, metodo_pago, estado_pedido)
);

COMMENT ON TABLE dw.dim_contexto_pedido IS
'Dimensión de baja cardinalidad construida con atributos contextuales de public.pedido.';

COMMENT ON COLUMN dw.dim_contexto_pedido.sk_contexto_pedido IS 'Llave subrogada de la dimensión.';
COMMENT ON COLUMN dw.dim_contexto_pedido.canal_dispositivo IS 'Canal o dispositivo usado para realizar el pedido.';
COMMENT ON COLUMN dw.dim_contexto_pedido.metodo_pago IS 'Método de pago utilizado.';
COMMENT ON COLUMN dw.dim_contexto_pedido.estado_pedido IS 'Estado del pedido en la fuente transaccional.';


-- ------------------------------------------------------------
-- 2.6 DimOperadorLogistico
-- ------------------------------------------------------------
CREATE TABLE dw.dim_operador_logistico (
    sk_operador          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_operador_origen   INTEGER UNIQUE,
    nombre_operador      VARCHAR(100) NOT NULL
);

COMMENT ON TABLE dw.dim_operador_logistico IS
'Dimensión de operadores logísticos construida a partir de public.operadorlogistico.';

COMMENT ON COLUMN dw.dim_operador_logistico.sk_operador IS 'Llave subrogada de la dimensión.';
COMMENT ON COLUMN dw.dim_operador_logistico.id_operador_origen IS 'Identificador del operador en la fuente transaccional.';
COMMENT ON COLUMN dw.dim_operador_logistico.nombre_operador IS 'Nombre del operador logístico.';


-- ------------------------------------------------------------
-- 2.7 DimContextoEnvio
-- ------------------------------------------------------------
CREATE TABLE dw.dim_contexto_envio (
    sk_contexto_envio    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region                VARCHAR(50),
    tipo_envio            VARCHAR(20),

    CONSTRAINT uq_dim_contexto_envio
        UNIQUE (region, tipo_envio)
);

COMMENT ON TABLE dw.dim_contexto_envio IS
'Dimensión de baja cardinalidad construida con región y tipo de envío provenientes de public.envio.';

COMMENT ON COLUMN dw.dim_contexto_envio.sk_contexto_envio IS 'Llave subrogada de la dimensión.';
COMMENT ON COLUMN dw.dim_contexto_envio.region IS 'Región asociada al envío.';
COMMENT ON COLUMN dw.dim_contexto_envio.tipo_envio IS 'Tipo de envío, por ejemplo Estándar o Express.';


-- ------------------------------------------------------------
-- 2.8 DimMotivoEvento
-- ------------------------------------------------------------
CREATE TABLE dw.dim_motivo_evento (
    sk_motivo_evento     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_evento           VARCHAR(20),
    motivo                VARCHAR(150),

    CONSTRAINT uq_dim_motivo_evento
        UNIQUE (tipo_evento, motivo)
);

COMMENT ON TABLE dw.dim_motivo_evento IS
'Dimensión de eventos posventa construida a partir de public.devolucioncancelacion.';

COMMENT ON COLUMN dw.dim_motivo_evento.sk_motivo_evento IS 'Llave subrogada de la dimensión.';
COMMENT ON COLUMN dw.dim_motivo_evento.tipo_evento IS 'Tipo de evento: Cancelación o Devolución.';
COMMENT ON COLUMN dw.dim_motivo_evento.motivo IS 'Motivo asociado al evento posventa.';


-- ============================================================
-- 3. MIEMBROS TÉCNICOS / ESPECIALES
-- ============================================================
-- Se usa la llave 0 para representar valores desconocidos,
-- no informados o no aplicables durante el ETL.

INSERT INTO dw.dim_tiempo (
    sk_tiempo, fecha, dia, nombre_dia, semana, mes, nombre_mes, trimestre, anio
)
VALUES (
    0, NULL, NULL, 'No aplica', NULL, NULL, 'No aplica', NULL, NULL
)
ON CONFLICT (sk_tiempo) DO NOTHING;


INSERT INTO dw.dim_cliente (
    sk_cliente, id_cliente_origen, nombre_cliente, tipo_cliente, fecha_registro
)
VALUES (
    0, NULL, 'No informado', 'No informado', NULL
)
ON CONFLICT (sk_cliente) DO NOTHING;


INSERT INTO dw.dim_producto (
    sk_producto, id_producto_origen, nombre_producto, nombre_categoria, nombre_marca
)
VALUES (
    0, NULL, 'No informado', 'No informado', 'No informado'
)
ON CONFLICT (sk_producto) DO NOTHING;


INSERT INTO dw.dim_campania (
    sk_campania, id_campania_origen, nombre_campania, tipo_descuento,
    valor_descuento, fecha_inicio, fecha_fin
)
VALUES (
    0, NULL, 'Sin campaña', 'No aplica', 0.00, NULL, NULL
)
ON CONFLICT (sk_campania) DO NOTHING;


INSERT INTO dw.dim_contexto_pedido (
    sk_contexto_pedido, canal_dispositivo, metodo_pago, estado_pedido
)
VALUES (
    0, 'No informado', 'No informado', 'No informado'
)
ON CONFLICT (sk_contexto_pedido) DO NOTHING;


INSERT INTO dw.dim_operador_logistico (
    sk_operador, id_operador_origen, nombre_operador
)
VALUES (
    0, NULL, 'No informado'
)
ON CONFLICT (sk_operador) DO NOTHING;


INSERT INTO dw.dim_contexto_envio (
    sk_contexto_envio, region, tipo_envio
)
VALUES (
    0, 'No informado', 'No informado'
)
ON CONFLICT (sk_contexto_envio) DO NOTHING;


INSERT INTO dw.dim_motivo_evento (
    sk_motivo_evento, tipo_evento, motivo
)
VALUES (
    0, 'No informado', 'No informado'
)
ON CONFLICT (sk_motivo_evento) DO NOTHING;


-- ============================================================
-- 4. TABLAS DE HECHOS
-- ============================================================

-- ------------------------------------------------------------
-- 4.1 FactPedido
-- Granularidad: una fila por pedido.
-- ------------------------------------------------------------
CREATE TABLE dw.fact_pedido (
    id_pedido             INTEGER PRIMARY KEY,

    sk_tiempo_pedido      INTEGER NOT NULL,
    sk_cliente            INTEGER NOT NULL,
    sk_campania           INTEGER NOT NULL,
    sk_contexto_pedido    INTEGER NOT NULL,

    cantidad_pedidos      INTEGER NOT NULL DEFAULT 1,
    monto_total           NUMERIC(12,2),

    CONSTRAINT fk_fact_pedido_tiempo
        FOREIGN KEY (sk_tiempo_pedido)
        REFERENCES dw.dim_tiempo(sk_tiempo),

    CONSTRAINT fk_fact_pedido_cliente
        FOREIGN KEY (sk_cliente)
        REFERENCES dw.dim_cliente(sk_cliente),

    CONSTRAINT fk_fact_pedido_campania
        FOREIGN KEY (sk_campania)
        REFERENCES dw.dim_campania(sk_campania),

    CONSTRAINT fk_fact_pedido_contexto
        FOREIGN KEY (sk_contexto_pedido)
        REFERENCES dw.dim_contexto_pedido(sk_contexto_pedido),

    CONSTRAINT ck_fact_pedido_cantidad
        CHECK (cantidad_pedidos = 1)
);

COMMENT ON TABLE dw.fact_pedido IS
'Tabla de hechos a nivel de pedido. Permite analizar cantidad de pedidos, monto total, ticket promedio y recurrencia de compra.';

COMMENT ON COLUMN dw.fact_pedido.id_pedido IS 'Dimensión degenerada e identificador del pedido en la fuente.';
COMMENT ON COLUMN dw.fact_pedido.cantidad_pedidos IS 'Medida aditiva con valor constante 1 por fila.';
COMMENT ON COLUMN dw.fact_pedido.monto_total IS 'Monto total del pedido proveniente de public.pedido.monto_total.';


-- ------------------------------------------------------------
-- 4.2 FactDetalleVenta
-- Granularidad: una fila por línea de producto del pedido.
-- ------------------------------------------------------------
CREATE TABLE dw.fact_detalle_venta (
    id_detalle             INTEGER PRIMARY KEY,
    id_pedido              INTEGER NOT NULL,

    sk_tiempo_pedido       INTEGER NOT NULL,
    sk_cliente             INTEGER NOT NULL,
    sk_campania            INTEGER NOT NULL,
    sk_producto            INTEGER NOT NULL,
    sk_contexto_pedido     INTEGER NOT NULL,

    cantidad               INTEGER NOT NULL,
    precio_venta_unitario  NUMERIC(10,2) NOT NULL,
    ingreso_bruto          NUMERIC(12,2) NOT NULL,
    costo_unitario         NUMERIC(10,2),
    costo_total            NUMERIC(12,2),
    margen_bruto           NUMERIC(12,2),

    CONSTRAINT fk_fact_detalle_tiempo
        FOREIGN KEY (sk_tiempo_pedido)
        REFERENCES dw.dim_tiempo(sk_tiempo),

    CONSTRAINT fk_fact_detalle_cliente
        FOREIGN KEY (sk_cliente)
        REFERENCES dw.dim_cliente(sk_cliente),

    CONSTRAINT fk_fact_detalle_campania
        FOREIGN KEY (sk_campania)
        REFERENCES dw.dim_campania(sk_campania),

    CONSTRAINT fk_fact_detalle_producto
        FOREIGN KEY (sk_producto)
        REFERENCES dw.dim_producto(sk_producto),

    CONSTRAINT fk_fact_detalle_contexto
        FOREIGN KEY (sk_contexto_pedido)
        REFERENCES dw.dim_contexto_pedido(sk_contexto_pedido),

    CONSTRAINT ck_fact_detalle_cantidad
        CHECK (cantidad > 0)
);

COMMENT ON TABLE dw.fact_detalle_venta IS
'Tabla de hechos a nivel de línea de pedido. Permite analizar productos, categorías, marcas, unidades, ingresos, costos y margen.';

COMMENT ON COLUMN dw.fact_detalle_venta.id_detalle IS 'Dimensión degenerada e identificador de DetallePedido en la fuente.';
COMMENT ON COLUMN dw.fact_detalle_venta.id_pedido IS 'Identificador degenerado del pedido al que pertenece la línea.';
COMMENT ON COLUMN dw.fact_detalle_venta.ingreso_bruto IS 'Equivale al subtotal de la línea de pedido.';
COMMENT ON COLUMN dw.fact_detalle_venta.costo_total IS 'Medida derivada: cantidad multiplicada por costo_unitario.';
COMMENT ON COLUMN dw.fact_detalle_venta.margen_bruto IS 'Medida derivada: ingreso_bruto menos costo_total.';


-- ------------------------------------------------------------
-- 4.3 FactEnvio
-- Granularidad: una fila por envío.
-- ------------------------------------------------------------
CREATE TABLE dw.fact_envio (
    id_envio                 INTEGER PRIMARY KEY,
    id_pedido                INTEGER NOT NULL UNIQUE,

    sk_tiempo_pedido         INTEGER NOT NULL,
    sk_tiempo_previsto       INTEGER NOT NULL,
    sk_tiempo_entrega_real   INTEGER NOT NULL,

    sk_operador              INTEGER NOT NULL,
    sk_contexto_envio        INTEGER NOT NULL,
    sk_contexto_pedido       INTEGER NOT NULL,

    cantidad_envios          INTEGER NOT NULL DEFAULT 1,
    dias_entrega             INTEGER,
    dias_desviacion          INTEGER,
    entrega_a_tiempo         SMALLINT,

    CONSTRAINT fk_fact_envio_tiempo_pedido
        FOREIGN KEY (sk_tiempo_pedido)
        REFERENCES dw.dim_tiempo(sk_tiempo),

    CONSTRAINT fk_fact_envio_tiempo_previsto
        FOREIGN KEY (sk_tiempo_previsto)
        REFERENCES dw.dim_tiempo(sk_tiempo),

    CONSTRAINT fk_fact_envio_tiempo_real
        FOREIGN KEY (sk_tiempo_entrega_real)
        REFERENCES dw.dim_tiempo(sk_tiempo),

    CONSTRAINT fk_fact_envio_operador
        FOREIGN KEY (sk_operador)
        REFERENCES dw.dim_operador_logistico(sk_operador),

    CONSTRAINT fk_fact_envio_contexto_envio
        FOREIGN KEY (sk_contexto_envio)
        REFERENCES dw.dim_contexto_envio(sk_contexto_envio),

    CONSTRAINT fk_fact_envio_contexto_pedido
        FOREIGN KEY (sk_contexto_pedido)
        REFERENCES dw.dim_contexto_pedido(sk_contexto_pedido),

    CONSTRAINT ck_fact_envio_cantidad
        CHECK (cantidad_envios = 1),

    CONSTRAINT ck_fact_envio_a_tiempo
        CHECK (entrega_a_tiempo IN (0, 1) OR entrega_a_tiempo IS NULL)
);

COMMENT ON TABLE dw.fact_envio IS
'Tabla de hechos a nivel de envío. Permite analizar tiempos de entrega y cumplimiento logístico.';

COMMENT ON COLUMN dw.fact_envio.id_envio IS 'Dimensión degenerada e identificador del envío en la fuente.';
COMMENT ON COLUMN dw.fact_envio.id_pedido IS 'Identificador del pedido asociado. La fuente define un envío por pedido.';
COMMENT ON COLUMN dw.fact_envio.dias_entrega IS 'Días transcurridos entre fecha_pedido y fecha_entrega_real.';
COMMENT ON COLUMN dw.fact_envio.dias_desviacion IS 'Diferencia en días entre fecha_entrega_real y fecha_prevista.';
COMMENT ON COLUMN dw.fact_envio.entrega_a_tiempo IS '1 si la entrega real fue en o antes de la fecha prevista; 0 si fue tardía; NULL si no aplica.';


-- ------------------------------------------------------------
-- 4.4 FactDevolucionCancelacion
-- Granularidad: una fila por evento posventa.
-- ------------------------------------------------------------
CREATE TABLE dw.fact_devolucion_cancelacion (
    id_evento               INTEGER PRIMARY KEY,
    id_detalle_origen       INTEGER NOT NULL,

    sk_tiempo_evento        INTEGER NOT NULL,
    sk_cliente              INTEGER NOT NULL,
    sk_campania             INTEGER NOT NULL,
    sk_producto             INTEGER NOT NULL,
    sk_contexto_pedido      INTEGER NOT NULL,
    sk_motivo_evento        INTEGER NOT NULL,

    cantidad_eventos        INTEGER NOT NULL DEFAULT 1,
    monto_reembolso         NUMERIC(12,2),

    CONSTRAINT fk_fact_evento_tiempo
        FOREIGN KEY (sk_tiempo_evento)
        REFERENCES dw.dim_tiempo(sk_tiempo),

    CONSTRAINT fk_fact_evento_cliente
        FOREIGN KEY (sk_cliente)
        REFERENCES dw.dim_cliente(sk_cliente),

    CONSTRAINT fk_fact_evento_campania
        FOREIGN KEY (sk_campania)
        REFERENCES dw.dim_campania(sk_campania),

    CONSTRAINT fk_fact_evento_producto
        FOREIGN KEY (sk_producto)
        REFERENCES dw.dim_producto(sk_producto),

    CONSTRAINT fk_fact_evento_contexto
        FOREIGN KEY (sk_contexto_pedido)
        REFERENCES dw.dim_contexto_pedido(sk_contexto_pedido),

    CONSTRAINT fk_fact_evento_motivo
        FOREIGN KEY (sk_motivo_evento)
        REFERENCES dw.dim_motivo_evento(sk_motivo_evento),

    CONSTRAINT ck_fact_evento_cantidad
        CHECK (cantidad_eventos = 1)
);

COMMENT ON TABLE dw.fact_devolucion_cancelacion IS
'Tabla de hechos a nivel de evento de devolución o cancelación asociado a una línea de pedido.';

COMMENT ON COLUMN dw.fact_devolucion_cancelacion.id_evento IS 'Dimensión degenerada e identificador del evento en la fuente.';
COMMENT ON COLUMN dw.fact_devolucion_cancelacion.id_detalle_origen IS 'Identificador de la línea de pedido afectada en la fuente.';
COMMENT ON COLUMN dw.fact_devolucion_cancelacion.cantidad_eventos IS 'Medida aditiva con valor constante 1 por evento.';
COMMENT ON COLUMN dw.fact_devolucion_cancelacion.monto_reembolso IS 'Monto reembolsado asociado al evento.';


-- ============================================================
-- 5. ÍNDICES SOBRE LLAVES FORÁNEAS
-- ============================================================
-- PostgreSQL no crea automáticamente índices para las FK.
-- Estos índices facilitan uniones y consultas analíticas.

CREATE INDEX IF NOT EXISTS idx_fact_pedido_tiempo
    ON dw.fact_pedido(sk_tiempo_pedido);

CREATE INDEX IF NOT EXISTS idx_fact_pedido_cliente
    ON dw.fact_pedido(sk_cliente);

CREATE INDEX IF NOT EXISTS idx_fact_pedido_campania
    ON dw.fact_pedido(sk_campania);

CREATE INDEX IF NOT EXISTS idx_fact_pedido_contexto
    ON dw.fact_pedido(sk_contexto_pedido);


CREATE INDEX IF NOT EXISTS idx_fact_detalle_tiempo
    ON dw.fact_detalle_venta(sk_tiempo_pedido);

CREATE INDEX IF NOT EXISTS idx_fact_detalle_cliente
    ON dw.fact_detalle_venta(sk_cliente);

CREATE INDEX IF NOT EXISTS idx_fact_detalle_campania
    ON dw.fact_detalle_venta(sk_campania);

CREATE INDEX IF NOT EXISTS idx_fact_detalle_producto
    ON dw.fact_detalle_venta(sk_producto);

CREATE INDEX IF NOT EXISTS idx_fact_detalle_contexto
    ON dw.fact_detalle_venta(sk_contexto_pedido);


CREATE INDEX IF NOT EXISTS idx_fact_envio_tiempo_pedido
    ON dw.fact_envio(sk_tiempo_pedido);

CREATE INDEX IF NOT EXISTS idx_fact_envio_tiempo_previsto
    ON dw.fact_envio(sk_tiempo_previsto);

CREATE INDEX IF NOT EXISTS idx_fact_envio_tiempo_real
    ON dw.fact_envio(sk_tiempo_entrega_real);

CREATE INDEX IF NOT EXISTS idx_fact_envio_operador
    ON dw.fact_envio(sk_operador);

CREATE INDEX IF NOT EXISTS idx_fact_envio_contexto_envio
    ON dw.fact_envio(sk_contexto_envio);

CREATE INDEX IF NOT EXISTS idx_fact_envio_contexto_pedido
    ON dw.fact_envio(sk_contexto_pedido);


CREATE INDEX IF NOT EXISTS idx_fact_evento_tiempo
    ON dw.fact_devolucion_cancelacion(sk_tiempo_evento);

CREATE INDEX IF NOT EXISTS idx_fact_evento_cliente
    ON dw.fact_devolucion_cancelacion(sk_cliente);

CREATE INDEX IF NOT EXISTS idx_fact_evento_campania
    ON dw.fact_devolucion_cancelacion(sk_campania);

CREATE INDEX IF NOT EXISTS idx_fact_evento_producto
    ON dw.fact_devolucion_cancelacion(sk_producto);

CREATE INDEX IF NOT EXISTS idx_fact_evento_contexto
    ON dw.fact_devolucion_cancelacion(sk_contexto_pedido);

CREATE INDEX IF NOT EXISTS idx_fact_evento_motivo
    ON dw.fact_devolucion_cancelacion(sk_motivo_evento);


-- ============================================================
-- 6. VERIFICACIÓN DE LA IMPLEMENTACIÓN
-- ============================================================

-- 6.1 Deben aparecer 12 tablas en el esquema dw.
SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'dw'
  AND table_type = 'BASE TABLE'
ORDER BY table_name;


-- 6.2 Comprobar que existen 8 dimensiones y 4 tablas de hechos.
SELECT
    COUNT(*) FILTER (WHERE table_name LIKE 'dim_%') AS dimensiones,
    COUNT(*) FILTER (WHERE table_name LIKE 'fact_%') AS hechos,
    COUNT(*) AS total_tablas
FROM information_schema.tables
WHERE table_schema = 'dw'
  AND table_type = 'BASE TABLE';


-- 6.3 Comprobar los miembros técnicos creados.
SELECT 'dim_tiempo' AS tabla, COUNT(*) AS registros FROM dw.dim_tiempo
UNION ALL
SELECT 'dim_cliente', COUNT(*) FROM dw.dim_cliente
UNION ALL
SELECT 'dim_producto', COUNT(*) FROM dw.dim_producto
UNION ALL
SELECT 'dim_campania', COUNT(*) FROM dw.dim_campania
UNION ALL
SELECT 'dim_contexto_pedido', COUNT(*) FROM dw.dim_contexto_pedido
UNION ALL
SELECT 'dim_operador_logistico', COUNT(*) FROM dw.dim_operador_logistico
UNION ALL
SELECT 'dim_contexto_envio', COUNT(*) FROM dw.dim_contexto_envio
UNION ALL
SELECT 'dim_motivo_evento', COUNT(*) FROM dw.dim_motivo_evento
ORDER BY tabla;


-- 6.4 Listar las llaves foráneas del modelo dimensional.
SELECT
    tc.table_name,
    tc.constraint_name,
    kcu.column_name,
    ccu.table_name AS tabla_referenciada,
    ccu.column_name AS columna_referenciada
FROM information_schema.table_constraints tc
JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name = kcu.constraint_name
   AND tc.constraint_schema = kcu.constraint_schema
JOIN information_schema.constraint_column_usage ccu
    ON tc.constraint_name = ccu.constraint_name
   AND tc.constraint_schema = ccu.constraint_schema
WHERE tc.constraint_type = 'FOREIGN KEY'
  AND tc.table_schema = 'dw'
ORDER BY tc.table_name, tc.constraint_name;


-- ============================================================
-- FIN DEL SCRIPT
-- ============================================================
